# this docker file can be used for both a daemon, miner and a wallet if needed
# we only have to set specific command or entrypoint inside the docker compose
# file to customize the behavior of the container when started.

# step 1: build the binary
FROM ubuntu:22.04 as builder

COPY . /usr/src/kryptokrona
WORKDIR /usr/src/kryptokrona

RUN chmod +x ./scripts/testnet/wait-for-it.sh ./scripts/testnet/docker-entrypoint.sh

# install build dependencies
RUN apt-get update && \
    apt-get install -y \
    build-essential \
    libssl-dev \
    libffi-dev \
    python3-dev \
    gcc-11 \
    g++-11 \
    git \
    cmake \
    librocksdb-dev \
    libboost-all-dev \
    libboost-system1.74.0 \
    libboost-filesystem1.74.0 \
    libboost-thread1.74.0 \
    libboost-date-time1.74.0 \
    libboost-chrono1.74.0 \
    libboost-regex1.74.0 \
    libboost-serialization1.74.0 \
    libboost-program-options1.74.0 \
    libicu70 \
    cron \
    rpcbind

# create the build directory
RUN mkdir build
WORKDIR /usr/src/kryptokrona/build

# build and install
RUN cmake -DCMAKE_CXX_FLAGS="-g0 -Os -fPIC -std=gnu++17" -DTEST_NET=ON .. && make

# step 2: create the final image
FROM ubuntu:22.04

WORKDIR /usr/src/kryptokrona

COPY --from=builder /usr/src/kryptokrona/start.sh .
COPY --from=builder /usr/src/kryptokrona/build/src/kryptokronad .
COPY --from=builder /usr/src/kryptokrona/build/src/xkrwallet .
COPY --from=builder /usr/src/kryptokrona/build/src/miner .

EXPOSE 11897
EXPOSE 11898

# create the directory for the daemon files
RUN mkdir -p src/blockloc
