version: '3'

services:
  node1:
    image: funkypenguin/turtlecoin
    container_name: turtletest-node1
    volumes:
      - ../turtlecoind:/var/lib/turtlecoind/
    networks:
      testnet:
        ipv4_address: 172.16.76.11
  
#  node2:
#    image: funkypenguin/turtlecoin
#    container_name: turtletest-node2
#    networks:
#      testnet:
#        ipv4_address: 172.16.76.12
  
#  node3:
#    image: funkypenguin/turtlecoin
#    container_name: turtletest-node3
#    networks:
#      testnet:
#        ipv4_address: 172.16.76.13

networks:
  testnet:
    ipam:
      config:
        - subnet: 172.16.76.0/24

