mod rpc;
mod trace;

const PBKDF2_ITERATIONS: i64 = 10000;
// const ADDRESS_BODY_LENGTH: i16 =
// const ADDRESS_REGEX: &str =
const HASH_REGEX: &str = "[a-fA-F0-9]{64}";

use clap::Parser;
use futures::{future, prelude::*};
use rpc::WalletRPC;
use std::net::{IpAddr, Ipv4Addr, SocketAddr};
use tarpc::{
    server::{self, incoming::Incoming, Channel},
    tokio_serde::formats::Json,
};
use trace::init_tracing;

#[derive(Parser)]
struct Flags {
    #[clap(long)]
    port: u16,
    rpc_bind_ip: String,
    enable_cors: Option<String>,
    rpc_password: Option<String>,
}

#[derive(Clone)]
pub struct WalletRPCServer(SocketAddr);

async fn spawn(fut: impl Future<Output = ()> + Send + 'static) {
    tokio::spawn(fut);
}

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let flags = Flags::parse();
    init_tracing("Kryptokrona Wallet RPC Server")?;

    let server_addr = (IpAddr::V4(Ipv4Addr::LOCALHOST), flags.port);

    // JSON transport is provided by the json_transport tarpc module. It makes it easy
    // to start up a serde-powered json serialization strategy over TCP.
    let mut listener = tarpc::serde_transport::tcp::listen(&server_addr, Json::default).await?;
    tracing::info!("Listening on port {}", listener.local_addr().port());
    listener.config_mut().max_frame_length(usize::MAX);
    listener
        // Ignore accept errors.
        .filter_map(|r| future::ready(r.ok()))
        .map(server::BaseChannel::with_defaults)
        // Limit channels to 1 per IP.
        .max_channels_per_key(1, |t| t.transport().peer_addr().unwrap().ip())
        // serve is generated by the service attribute. It takes as input any type implementing
        // the generated trait.
        .map(|channel| {
            let server = WalletRPCServer(channel.transport().peer_addr().unwrap());
            channel.execute(WalletRPC::serve(server)).for_each(spawn)
        })
        // Max 10 channels.
        .buffer_unordered(10)
        .for_each(|_| async {})
        .await;

    Ok(())
}
