---
- name: Install 7zip
  apt:
    name: "{{ item }}"
    update_cache: true
    state: present
  with_items:
    - p7zip-full
    - p7zip-rar

- name: Checkout repo
  git: repo=https://github.com/kryptokrona/kryptokrona.git
    dest=/root/tmp/checkout
    update=yes
    accept_hostkey=yes
    clone=false
    update=false
  register: gitresult

- name: Check that the bootstrap already exists
  stat:
    path: "/home/{{ username }}/bootstrap.7z"
  register: stat_result

- name: Download Boostrap
  when: kryptokrona_node_boostrap | length > 0 and not stat_result.stat.exists
  get_url:
    url: "{{ kryptokrona_node_boostrap }}"
    dest: "/home/{{ username }}/bootstrap.7z"
    mode: 0755

- name: Recursively Change Ownership of .kryptokrona Directory
  file:
    path: "/home/{{ username }}/.kryptokrona"
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Extract Boostrap
  when: kryptokrona_node_boostrap | length > 0 and not stat_result.stat.exists
  shell: "7z x *.7z -o/home/{{ username }}"

- name: Create Kryptokrona Node Container
  docker_container:
    name: "{{ docker_node_container_name }}"
    image: "{{ docker_kryptokona_image }}:{{ gitresult.after[:7] }}"
    command: /bin/echo success
    state: present
    force_kill: yes
    recreate: yes
    volumes:
      - "/home/{{ username }}/.kryptokrona:/home/root/.kryptokrona"
    networks:
      - name: "host"

- name: Start Kryptokrona Node Container
  docker_container:
    name: "{{ docker_node_container_name }}"
    image: "{{ docker_kryptokona_image }}:{{ gitresult.after[:7] }}"
    command: "/usr/src/kryptokrona/start.sh"
    volumes:
      - "/home/{{ username }}/.kryptokrona:/home/root/.kryptokrona"
    networks:
      - name: "host"
