# This is the new workflow replacing 'master-ci.yml' for the C++ -> Rust transition

name: build

on:
  push:
    branches:
      - rust # change this to master later
  pull_request:
    branches:
      - rust # change this to master later
    paths-ignore:
      - "**/README.md"
      - "**/LICENSE"
      - "**/SECURITY.md"
      - "**/.gitignore"
      - "**/resources/**"
      - "**/.github/ISSUE_TEMPLATE/**"

jobs:
  build:
    name: build ${{ matrix.config.name }} (${{ matrix.config.arch }})
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: true
      matrix:
        config:
          - {
              name: "macos",
              os: macos-latest,
              args: "aarch64-apple-darwin",
              arch: arm64,
            }
          - {
              name: "macos",
              os: macos-latest,
              args: "x86_64-apple-darwin",
              arch: x86_64,
            }
          # we will add ubuntu and windows here once we get macos working

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Install Dependencies
        if: matrix.config.name == 'macos'
        run: |
          rustup target add ${{ matrix.config.args }}
          brew install -y protobuf

      - name: Cache Cargo Dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run Clippy
        run: cargo clippy --all-features --target ${{ matrix.config.args }}

      - name: Build Project
        run: cargo build --release --target ${{ matrix.config.args }}

      - name: Run Tests
        run: cargo test --target ${{ matrix.config.args }}
